services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  papi-digitalizer:
    build: 
      context: .
      network: host
    container_name: papi_app
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - OLLAMA_HOST=http://localhost:11434
      - DEBUG_MODE=1
      - CLEAN_SCANS=0
    network_mode: "host"
    command: tail -f /dev/null

volumes:
  ollama_data: